apiVersion: v1
data:
  my-nginx-config.conf: |
    server {
        listen 80;
        listen 443;
        server_name www.kubia-example.com;
        ssl_certificate certs/httpd.crt;
        ssl_certificate_key certs/httpd.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!MD5;
        gzip on;
        gzip_types text/plain application/xml;

        location / {
            root /usr/share/nginx/html;
            index index.htm index.html;
        }
    } 
  sleep-interval: |
    12
kind: ConfigMap
metadata:
  name: fortune-config1
  namespace: default
