apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
