apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  type: NodePort
  selector:
    pod-template-hash: 657c9f55d4
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
