apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu

spec:
  tolerations:
    - key: node-type
      operator: Equal
      value: production
      effect: NoSchedule
  nodeSelector:
    gpu: "true"
  containers:
    - image: luksa/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
